Update requirements_k8s_el9.txt
added bcrypt==3.2.2 due to this error 

TASK [ocp4_workload_authentication : Add admin user to htpasswd file] **********
Thursday 13 November 2025  07:20:28 +0000 (0:00:00.817)       1:08:59.430 ***** 
fatal: [bastion-mgcfg]: FAILED! => {"changed": false, "module_stderr": "Shared connection to bastion-mgcfg.eastus.cloudapp.azure.com closed.\\r\\n", "module_stdout": "(trapped) error reading bcrypt version\\r\\nTraceback (most recent call last):\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/handlers/bcrypt.py\\", line 620, in _load_backend_mixin\\r\\n    version = _bcrypt.__about__.__version__\\r\\nAttributeError: module 'bcrypt' has no attribute '__about__'\\r\\nTraceback (most recent call last):\\r\\n  File \\"/home/azure/.ansible/tmp/ansible-tmp-1763018428.827903-3555-49388111691738/AnsiballZ_htpasswd.py\\", line 107, in <module>\\r\\n    _ansiballz_main()\\r\\n  File \\"/home/azure/.ansible/tmp/ansible-tmp-1763018428.827903-3555-49388111691738/AnsiballZ_htpasswd.py\\", line 99, in _ansiballz_main\\r\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\r\\n  File \\"/home/azure/.ansible/tmp/ansible-tmp-1763018428.827903-3555-49388111691738/AnsiballZ_htpasswd.py\\", line 47, in invoke_module\\r\\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.htpasswd', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.htpasswd', _modlib_path=modlib_path),\\r\\n  File \\"/usr/lib64/python3.9/runpy.py\\", line 225, in run_module\\r\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\r\\n  File \\"/usr/lib64/python3.9/runpy.py\\", line 97, in _run_module_code\\r\\n    _run_code(code, mod_globals, init_globals,\\r\\n  File \\"/usr/lib64/python3.9/runpy.py\\", line 87, in _run_code\\r\\n    exec(code, run_globals)\\r\\n  File \\"/tmp/ansible_community.general.htpasswd_payload_v1zshseq/ansible_community.general.htpasswd_payload.zip/ansible_collections/community/general/plugins/modules/htpasswd.py\\", line 117, in <module>\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/apache.py\\", line 476, in <module>\\r\\n    htpasswd_defaults = _init_default_schemes()\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/apache.py\\", line 446, in _init_default_schemes\\r\\n    bcrypt = \\"bcrypt\\" if registry.has_backend(\\"bcrypt\\") else None\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/registry.py\\", line 483, in has_backend\\r\\n    hasher.get_backend()\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/utils/handlers.py\\", line 2088, in get_backend\\r\\n    cls.set_backend()\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/utils/handlers.py\\", line 2163, in set_backend\\r\\n    return cls.set_backend(name, dryrun=dryrun)\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/utils/handlers.py\\", line 2188, in set_backend\\r\\n    cls._set_backend(name, dryrun)\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/utils/handlers.py\\", line 2311, in _set_backend\\r\\n    super(SubclassBackendMixin, cls)._set_backend(name, dryrun)\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/utils/handlers.py\\", line 2224, in _set_backend\\r\\n    ok = loader(**kwds)\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/handlers/bcrypt.py\\", line 626, in _load_backend_mixin\\r\\n    return mixin_cls._finalize_backend_mixin(name, dryrun)\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/handlers/bcrypt.py\\", line 421, in _finalize_backend_mixin\\r\\n    if detect_wrap_bug(IDENT_2A):\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/handlers/bcrypt.py\\", line 380, in detect_wrap_bug\\r\\n    if verify(secret, bug_hash):\\r\\n  File \\"/opt/virtualenvs/k8s/lib64/python3.9/site-packages/passlib/utils/handlers.py\\", line 792, in veri