Update ee-minimal-rhel8 to latest
Fixes the error:

> dnf update -y
Problem 1: package glibc-gconv-extra-2.28-196.el8.x86_64 requires glibc(x86-64) = 2.28-196.el8, but none of the providers can be installed
  - cannot install both glibc-2.28-197.el8.x86_64 and glibc-2.28-196.el8.x86_64
  - cannot install the best update candidate for package glibc-gconv-extra-2.28-184.el8.x86_64
  - cannot install the best update candidate for package glibc-2.28-184.el8.x86_64
 Problem 2: problem with installed package glibc-gconv-extra-2.28-184.el8.x86_64
  - package glibc-gconv-extra-2.28-184.el8.x86_64 requires glibc-common = 2.28-184.el8, but none of the providers can be installed
  - package glibc-gconv-extra-2.28-189.el8.x86_64 requires glibc-common = 2.28-189.el8, but none of the providers can be installed
  - package glibc-gconv-extra-2.28-196.el8.x86_64 requires glibc-common = 2.28-196.el8, but none of the providers can be installed
  - cannot install both glibc-common-2.28-197.el8.x86_64 and glibc-common-2.28-184.el8.x86_64
  - cannot install both glibc-common-2.28-197.el8.x86_64 and glibc-common-2.28-189.el8.x86_64
  - cannot install both glibc-common-2.28-197.el8.x86_64 and glibc-common-2.28-196.el8.x86_64
  - cannot install the best update candidate for package glibc-common-2.28-184.el8.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Error: error building at STEP "RUN assemble": error while running runtime: exit status 1