Update multicloud EE to v0.0.6 (#4615)
* Add azure and ansible.netcommon collections to EEs

* use ansible.utils in place of ansible.netcommon

* Fix public image by installing ansible-core pkg

- Fix collection routing by install the ansible pkg
- add vim and find binary
- add ansible.netcommon

* Update changelog in readme

* Add dnspython to python requirements

dnspython is needed for equinix cloud provider.
EE: ee-multicloud and multicloud public

* Use ansible-runner:devel to have a better ansible

ansible-runner:stable-2.12-latest has 2.12.3 which has the following
bugs:

(ipaddr filter name-routing not working)

https://github.com/ansible/ansible/issues/77192#issuecomment-1058159370

https://github.com/ansible/ansible/issues/77244

Use devel.

Remove pin of ansible-core in requirements.txt, as it's not necessary.
Remove ansible-core in pkg as it's not necessary.

* Update ee-minimal-rhel8 to latest

Fixes the error:

> dnf update -y
Problem 1: package glibc-gconv-extra-2.28-196.el8.x86_64 requires glibc(x86-64) = 2.28-196.el8, but none of the providers can be installed
  - cannot install both glibc-2.28-197.el8.x86_64 and glibc-2.28-196.el8.x86_64
  - cannot install the best update candidate for package glibc-gconv-extra-2.28-184.el8.x86_64
  - cannot install the best update candidate for package glibc-2.28-184.el8.x86_64
 Problem 2: problem with installed package glibc-gconv-extra-2.28-184.el8.x86_64
  - package glibc-gconv-extra-2.28-184.el8.x86_64 requires glibc-common = 2.28-184.el8, but none of the providers can be installed
  - package glibc-gconv-extra-2.28-189.el8.x86_64 requires glibc-common = 2.28-189.el8, but none of the providers can be installed
  - package glibc-gconv-extra-2.28-196.el8.x86_64 requires glibc-common = 2.28-196.el8, but none of the providers can be installed
  - cannot install both glibc-common-2.28-197.el8.x86_64 and glibc-common-2.28-184.el8.x86_64
  - cannot install both glibc-common-2.28-197.el8.x86_64 and glibc-common-2.28-189.el8.x86_64
  - cannot install both glibc-common-2.28-197.el8.x86_64 and glibc-common-2.28-196.el8.x86_64
  - cannot install the best update candidate for package glibc-common-2.28-184.el8.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Error: error building at STEP "RUN assemble": error while running runtime: exit status 1