Bump RHEL Golden Image to RHEL 9.4 for ansible-automation-platform (#8694)
* Bump RHEL Golden Image to RHEL 9.4 for ansible-automation-platform

* Partial rollback of 2d1a02bcc7b59ccc7f9d2f600f79c567b0ffd20b which breaks jinja code

* Replace certbot RPM packages through pip

to avoid AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
in role aap_pah_cert_issue